INSERT INTO Produtos (id, nome, tipo, genero, tamanho, cor, tecido)

VALUES (2, "camisa time", "camisa", "masculino", "G", "azul", "la")
VALUES (3, "camisa pijama", "camisa", "feminina", "M", "preta", "la")
VALUES (4, "camisa academia", "camisa", "masculino", "G", "azul", "la")
VALUES (5, "camisa frio", "camisa", "feminina", "P", "rosa", "la")
VALUES (6, "camisa verao", "camisa", "masculino", "G", "azul", "la")
VALUES (7, "camisa outono", "camisa", "feminina", "M", "amarela", "la")
VALUES (8, "camisa inverno", "camisa", "masculino", "G", "azul", "la")
VALUES (9, "camisa primavera", "camisa", "feminina", "G", "vinho", "la")
VALUES (10, "camisa summer", "camisa", "masculino", "P", "azul", "la")
VALUES (11, "camisa cool", "camisa", "masculino", "P", "turquesa", "la")
VALUES (12, "camisa todo", "camisa", "feminina", "M", "azul", "la")
VALUES (13, "camisa serie", "camisa", "feminina", "M", "pardo", "la")
VALUES (14, "camisa old", "camisa", "masculino", "G", "azul", "la")
VALUES (15, "camisa future", "camisa", "masculino", "G", "azul", "la")
